name: Go CI

on:
  pull_request

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  tests:
    runs-on: self-hosted
    timeout-minutes: 17
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: v1.24.0
          cache-dependency-path: ./go.sum
      - name: Generate code
        run: |
          make generate
          make build
      - name: Dependencies
        working-directory: ./
        run: go mod tidy
      - name: Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
      - name: Run tests
        run: |
          go test -v -race -timeout 5m -tags='integration_test' ./...
